name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: make


    - name: Install dependencies
      run: make

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.9.1
      with:
        node-version: '18' # optional
  
          
    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
