name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Check that the Makefile parses correctly
    - name: Dry run build
      run: make -n -f flightControlSystem.mk
